"""Add total_reviews column to ProfessionalProfile

Revision ID: 0269bfbad80d
Revises: 1a1ba635e6e5
Create Date: 2024-11-10 02:50:04.961660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0269bfbad80d'
down_revision = '1a1ba635e6e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_reviews', sa.Integer(), nullable=True))

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_text', sa.Text(), nullable=False))
        batch_op.drop_column('message')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', mysql.TEXT(), nullable=False))
        batch_op.drop_column('review_text')

    with op.batch_alter_table('professional_profile', schema=None) as batch_op:
        batch_op.drop_column('total_reviews')

    # ### end Alembic commands ###
