"""Reordered columns in ProfessionalProfile

Revision ID: 1a1ba635e6e5
Revises: 2c5c7cde8290
Create Date: 2024-11-09 19:22:51.879463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a1ba635e6e5'
down_revision = '2c5c7cde8290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_profile', schema=None) as batch_op:
        batch_op.alter_column('profile_completed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('availability_status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('available', 'unavailable', name='availability_status_enum'),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    with op.batch_alter_table('professional_profile', schema=None) as batch_op:
        batch_op.alter_column('availability_status',
               existing_type=sa.Enum('available', 'unavailable', name='availability_status_enum'),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('profile_completed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    # ### end Alembic commands ###
