"""empty message

Revision ID: 2c5c7cde8290
Revises: 77db6dbf28d5
Create Date: 2024-11-09 18:23:34.463799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c5c7cde8290'
down_revision = '77db6dbf28d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint('booking_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('booking_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'client_profile', ['client_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'professional_profile', ['professional_id'], ['user_id'])

    with op.batch_alter_table('client_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_profile', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('booking_ibfk_1', 'user', ['client_id'], ['id'])
        batch_op.create_foreign_key('booking_ibfk_2', 'user', ['professional_id'], ['id'])

    # ### end Alembic commands ###
