"""empty message

Revision ID: 77db6dbf28d5
Revises: 80fd1f91850f
Create Date: 2024-11-08 17:15:47.971599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '77db6dbf28d5'
down_revision = '80fd1f91850f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('professional_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('scheduled_time', mysql.DATETIME(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='bookings_ibfk_3'),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], name='bookings_ibfk_1'),
    sa.ForeignKeyConstraint(['professional_id'], ['user.id'], name='bookings_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
