"""recreate bookings and users tables

Revision ID: b26b3db4611f
Revises: 
Create Date: 2024-11-08 17:00:27.347950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b26b3db4611f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('client_profile_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('id')

    with op.batch_alter_table('professional_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('profile_picture',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.drop_constraint('professional_profile_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('professional_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('professional_profile_ibfk_1', 'user', ['id'], ['id'])
        batch_op.alter_column('profile_picture',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.drop_column('user_id')

    with op.batch_alter_table('client_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('client_profile_ibfk_1', 'user', ['id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
